# -*- coding: utf-8 -*-
"""prakalgo5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdpT4ngn6ERpI811009Y-wa3qALRW77S
"""

print("@@    @@  @@@@@@   @@             @@  @@  @@@@       @@")
print("@@   @@   @@        @@           @@   @@  @@  @@     @@")
print("@@ @@     @@         @@         @@    @@  @@   @@    @@")
print("@@@       @@@@@@      @@       @@     @@  @@    @@   @@")
print("@@ @@     @@           @@     @@      @@  @@     @@  @@")
print("@@   @@   @@            @@   @@       @@  @@      @@ @@")
print("@@    @@  @@@@@@         @@@@@        @@  @@       @@@@")
def generate_number_sequence(n, first, second):
    sequence = []
    for i in range(n):
        if i == 0:
            sequence.append(first)
        elif i == 1:
            sequence.append(second)
        else:
            next_number = sequence[i - 1] + sequence[i - 2]
            sequence.append(next_number)
    return sequence

def main():
    try:
        n = int(input("Masukkan jumlah bilangan dalam deret: "))
        first = int(input("Masukkan bilangan pertama: "))
        second = int(input("Masukkan bilangan kedua: "))

        if n < 2:
            print("Jumlah bilangan harus lebih besar atau sama dengan 2.")
        else:
            result = generate_number_sequence(n, first, second)
            print("Deret Bilangan:")
            for num in result:
                print(num)
    except ValueError:
        print("Input tidak valid. Pastikan Anda memasukkan bilangan bulat.")

if __name__ == "__main__":
    main()

jam_masuk = int(input("Jam masuk kantor: "))
menit_masuk = int(input("Menit masuk kantor: "))
jam_keluar = int(input("Jam keluar kantor: "))
menit_keluar = int(input("Menit keluar kantor: "))
jam_kerja = jam_keluar - jam_masuk
if menit_keluar < menit_masuk:
    jam_kerja -= 1
gaji_per_hari = 175000
lembur = 0
if jam_kerja > 8:
    lembur = (jam_kerja - 8) * 15000
    jam_kerja = 8

print(f"Selamat {jam_masuk:02d}:{menit_masuk:02d}")
print(f"Jam keluar kerja: {jam_keluar:02d}:{menit_keluar:02d}")
print("----- rincian gaji -----")
print(f"Waktu kerja: {jam_kerja} jam ({jam_masuk:02d}:{menit_masuk:02d} sd {jam_keluar:02d}:{menit_keluar:02d})")
print(f"Gaji perhari: Rp {gaji_per_hari}")
print(f"Lembur: Rp {lembur} ({jam_kerja - 8} jam x @Rp 15.000)")